config/routes.rb
Rails.application.routes.draw do

root  'blog#list'
  get 'blog/new' => 'blog#new', as: :new_blog
  get 'blog/:id' => 'blog#view', as: :blog
  post 'blog' => 'blog#create', as: :personal_blogs
  get 'blog/:id/edit' => 'blog#edit', as: :edit_blog
  patch 'blog/:id' => 'blog#update'
  delete 'blog/:id' => 'blog#delete'

end

app/models/personal_blog.rb
class Personal_Blog < ActiveRecord::Base
  validates :title, :subtitle,:author, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def list
    @blog= Personal_Blog.all
  end

  def view
    @blog= Personal_Blog.find_by id: params[:id]
  end
  def new
    @blog= Personal_Blog.new
  end

def create
  @blog=Personal_Blog.new
  # set the values
  @blog.title = params[:personal_blog][:title]
  @blog.author = params[:personal_blog][:author]
  @blog.subtitle = params[:personal_blog][:subtitle]
  # save it
  if @blog.save
    # redirect to "/books"
    redirect_to blog_path(id: @blog.id)
  else
    render :new
  end
end

  def edit
    @blog = Personal_Blog.find_by id: params[:id]
  end
  def update
    # instantiant / Find
    @blog = Personal_Blog.find_by id: params[:id]
    # set values
    @blog.title = params[:personal_blog][:title]
    @blog.author = params[:personal_blog][:author]
    @blog.subtitle = params[:personal_blog][:subtitle]

    # save it
    if @blog.save
      # redirect to "/blogs"
      redirect_to root_path
    else
      render :edit
    end
  end



  def delete
  @blog = Personal_Blog.find_by id: params[:id]
  @blog.destroy
  redirect_to root_path
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<div class="dreamerview"><p>The Dreamer, The Believer </p></div>
<nav> <p><%=link_to "Home", root_path, class:"Home" %></p>
<p><%=link_to "New Post", new_blog_path, class:"NP" %></p>
<p>TBD</p>
<p>TBD</p></nav>
<body>
  <% if @blog.errors.any? %>
  <% @blog.errors.full_messages.each do |error| %>
  <strong><%= error %></strong>
  <% end %>
<% end %>
      <%= form_for @blog, url: blog_path(id: @blog.id) do |f| %>
      <div class="newform">
      <p>Insert Title<p><%= f.text_area :title, cols: "30", rows: "1"%></p></p>
      <p>Insert Subtitle<p><%= f.text_area :subtitle, cols: "30", rows:"1" %></p></p>
      <p>Insert Author<p><%= f.text_area :author, cols: "15", rows:"1"%></p></p>
      <p><%= f.submit class:"submit" %></p>
      <% end %></div>
</body>

app/views/blog/list.html.erb
<head>
<link href='https://fonts.googleapis.com/css?family=Tangerine:700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="dreamer"><p>The Dreamer, The Believer </p></div>
  <div class="byzaki"> <p>By Zaki Ahmed </p></div>
<nav> <p><%=link_to "Home", root_path, class:"Home" %></p>
<p><%=link_to "New Post", new_blog_path, class:"NP" %></p>
<p>TBD</p>
<p>TBD</p></nav>
<img src="http://i854.photobucket.com/albums/ab108/The_Big_Zukini/bbq1.jpg" alt="" />
<% @blog.each do |blog| %>
<div class="posts">
<p><%= link_to blog_path(id: blog.id), class:"Title" do %><%= blog.title %><% end %> </p>
<p class="subtitle"><%= blog.subtitle %></p>
<p class="auth">By <%= blog.author %></p>
<% end %>
</div>
</body>

app/views/blog/new.html.erb
<head>
  <link href='https://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="dreamerview"><p>The Dreamer, The Believer </p></div>
<nav> <p><%=link_to "Home", root_path, class:"Home" %></p>
<p><%=link_to "New Post", new_blog_path, class:"NP" %></p>
<p>TBD</p>
<p>TBD</p></nav>
<% if @blog.errors.any? %>
<% @blog.errors.full_messages.each do |error| %>
<strong><%= error %></strong>
<% end %>
<% end %>
<%= form_for @blog do |f| %>
<div class="newform">
<p>Insert Title<p><%= f.text_area :title, cols: "30", rows: "1"%></p></p>
<p>Insert Subtitle<p><%= f.text_area :subtitle, cols: "30", rows:"1" %></p></p>
<p>Insert Author<p><%= f.text_area :author, cols: "15", rows:"1"%></p></p>
<p><%= f.submit class:"submit"%></p>
<% end %></div>
</body>

app/views/blog/view.html.erb
<head>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="dreamerview"><p>The Dreamer, The Believer </p></div>
<nav> <p><%=link_to "Home", root_path, class:"Home" %></p>
<p><%=link_to "New Post", new_blog_path, class:"NP" %></p>
<p>TBD</p>
<p>TBD</p></nav>
<div class="post">
<p><%= @blog.title %> <p><div class="sub"><p><%= @blog.subtitle %></p> <p>by<%= @blog.author %></p> </div></p>

<div class="edit"><%= link_to "Edit", edit_blog_path(id: @blog.id), class: "Editbttn"%></div>
<div class="delete"><%= link_to "Delete", blog_path(id: @blog.id), method: :delete, class: "deletebttn", data: {confirm: "Are you sure you want to delete?"}%></div>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PersonalBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>